### ISSUE TITLE
Deal into new stack error

### ISSUE THREAD

**Issue by elemoine** [emilysmiddleton/advent-of-code-2019#1]
Hi. Thanks a lot for this page.

I think there is an error in your "deal into new stack" operation. You say (1 - x) mod m while I think it's (-1 - x) mod m.

**Comment by emilysmiddleton** [comment]
You're right. The implementation is ok, because that's doing `(x * -1) - 1`
But I tried to make this more consistent to the other operations in the write-up and got this wrong!

**Comment by elemoine** [comment]
Thank you. FYI, and maybe others', I implemented your technique in Python: https://github.com/elemoine/adventofcode/blob/master/2019/day22/part2.py.
